name: Publish on npm

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish client
        run: |
          yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version
          yarn install
          yarn build
          cp .npmrc package.json README.md dist/
          cd dist
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
